<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Student;
use App\Models\Batch;
use App\Models\Role;
use App\Models\Attendance;
use App\Models\ExamResult;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class StudentManagementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $studentRole = Role::where('slug', 'student')->first();

        // Ensure we seed at least one student for EVERY class (1-12)
        foreach (range(1, 12) as $class) {
            // Find a course for this class
            $course = \App\Models\Course::where('class', (string)$class)->first();

            if (!$course) {
                // Should not happen if CourseSeeder runs first, but safety check
                continue;
            }

            // Find valid batches for this course
            $batches = \App\Models\Batch::where('course_id', $course->id)->get();
            
            if ($batches->isEmpty()) {
                continue; 
            }

            // Local images for students
            $studentImages = [
                '/images/team-kawsar.jpg',
                '/images/team-mikdad.jpg',
                '/images/team-galib.jpg',
                '/images/team-hasibur.jpg',
                '/images/team-hafez.jpg',
                '/images/team-happy.jpg',
                '/images/team-member-1.jpg',
                '/images/team-jems.jpg',
                '/images/team-lev.jpg',
                '/images/team-whatsapp-1.jpg',
            ];

            // Create 1-3 students for this class
            $studentCount = rand(1, 3);
            
            for ($i = 0; $i < $studentCount; $i++) {
                $batch = $batches->random();
                
                // Create unique user
                $email = "student_class{$class}_{$i}@example.com";
                $name = "Student Class $class - " . ($i + 1);
                
                $user = User::firstOrCreate(
                    ['email' => $email],
                    [
                        'name' => $name,
                        'password' => Hash::make('password'),
                    ]
                );

                if ($studentRole && !$user->hasRole('student')) {
                    $user->roles()->attach($studentRole->id);
                }

                // Create Student Profile with all required fields
                $student = Student::where('user_id', $user->id)->first();
                
                if (!$student) {
                    $student = Student::create([
                        'user_id' => $user->id,
                        'batch_id' => $batch->id,
                        'name_bn' => $name, // Set the Bengali name field
                        'class' => (string)$class,
                        'roll' => str_pad(rand(1, 50), 3, '0', STR_PAD_LEFT),
                        'section' => collect(['A', 'B', 'C', 'D'])->random(),
                        'group' => $class >= 9 ? collect(['Science', 'Commerce', 'Arts', 'Humanities'])->random() : null,
                        'shift' => collect(['Morning', 'Day', 'Evening'])->random(),
                        // registration_no will be auto-generated by the model's boot method
                        'course_name' => $course->name, // Legacy field
                        'phone' => '017' . str_pad((string)$class, 2, '0', STR_PAD_LEFT) . rand(100000, 999999),
                        'profile_image' => collect($studentImages)->random(),
                        'featured' => rand(1, 10) === 1, // Randomly mark ~10% as featured
                        'gender' => collect(['Male', 'Female'])->random(),
                        'blood_group' => collect(['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'])->random(),
                    ]);
                }

                     // Seed Attendance (Last 10 days)
                for ($j = 0; $j < 5; $j++) {
                    Attendance::updateOrCreate(
                        [
                            'student_id' => $student->id,
                            'date' => Carbon::now()->subDays($j)->toDateString(),
                        ],
                        [
                            'batch_id' => $student->batch_id,
                            'status' => collect(['present', 'present', 'present', 'absent'])->random(),
                        ]
                    );
                }

                // Seed Exam Results
                $subjects = ['Mathematics', 'English', 'Science'];
                foreach ($subjects as $subject) {
                    // Find or create an exam for this subject and batch
                    $exam = \App\Models\Exam::firstOrCreate(
                        [
                            'title' => $subject . ' - Term Exam',
                            'batch_id' => $student->batch_id,
                        ],
                        [
                            'type' => 'mcq',
                            'course_id' => $student->batch->course_id ?? null,
                            'total_marks' => 100,
                            'pass_marks' => 40,
                            'duration_minutes' => 60,
                            'status' => 'active',
                            'instructions' => 'Read all questions carefully.',
                        ]
                    );

                    $marks = rand(40, 99);
                    $grade = $marks >= 80 ? 'A+' : ($marks >= 70 ? 'A' : ($marks >= 60 ? 'A-' : 'B'));

                    ExamResult::updateOrCreate(
                        [
                            'student_id' => $student->id,
                            'exam_id' => $exam->id,
                        ],
                        [
                            'subject_name' => $subject,
                            'marks' => $marks,
                            'obtained_marks' => $marks,
                            'total_marks' => 100,
                            'grade' => $grade,
                        ]
                    );
                }
            }
        }
        
        // Add a few random "cool" students with images/real names just for demo if they don't exist
        $demoStudents = [
            [
                'name' => 'Demo Student',
                'email' => 'student@gmail.com',
                'class' => '10',
                'image' => '/images/team-kawsar.jpg',
            ],
            [
                'name' => 'Rahim Ahmed',
                'email' => 'rahim@example.com',
                'class' => '10',
                'image' => '/images/team-mikdad.jpg',
            ],
            [
                'name' => 'Fatima Begum',
                'email' => 'fatima@example.com',
                'class' => '11',
                'image' => '/images/team-galib.jpg',
            ]
        ];

        foreach($demoStudents as $data) {
             // Find course/batch for this class
             $course = \App\Models\Course::where('class', $data['class'])->first();
             if(!$course) continue;
             $batch = \App\Models\Batch::where('course_id', $course->id)->inRandomOrder()->first();
             if(!$batch) continue;

             $user = User::firstOrCreate(
                ['email' => $data['email']],
                [
                    'name' => $data['name'],
                    'password' => Hash::make('password'),
                ]
            );

            if ($studentRole && !$user->hasRole('student')) {
                $user->roles()->attach($studentRole->id);
            }

            $student = Student::where('user_id', $user->id)->first();
            
            if (!$student) {
                Student::create([
                    'user_id' => $user->id,
                    'batch_id' => $batch->id,
                    'name_bn' => $data['name'], // Set the Bengali name field
                    'class' => $data['class'],
                    'roll' => str_pad(rand(1, 50), 3, '0', STR_PAD_LEFT),
                    'section' => collect(['A', 'B', 'C', 'D'])->random(),
                    'group' => $data['class'] >= 9 ? collect(['Science', 'Commerce', 'Arts', 'Humanities'])->random() : null,
                    'shift' => collect(['Morning', 'Day', 'Evening'])->random(),
                    // registration_no will be auto-generated by the model's boot method
                    'course_name' => $course->name,
                    'phone' => '01700000000',
                    'profile_image' => $data['image'],
                    'featured' => true, // Mark demo students as featured
                    'gender' => collect(['Male', 'Female'])->random(),
                    'blood_group' => collect(['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'])->random(),
                ]);
            }
        }
    }
}
